const API='http://127.0.0.1:8000';
const $=id=>document.getElementById(id); let selected=null;
async function health(){try{const r=await fetch(API+'/health');if(!r.ok)throw 0; $('status').textContent='API online';$('status').classList.add('ok')}catch{$('status').textContent='API offline'}}
function choose(file){selected=file||null;$('filename').textContent=selected?selected.name:'No file selected';$('analyze').disabled=!selected;$('error').textContent=''}
$('file').addEventListener('change',e=>choose(e.target.files[0]));
['dragenter','dragover'].forEach(x=>$('drop').addEventListener(x,e=>{e.preventDefault();$('drop').classList.add('drag')}));
['dragleave','drop'].forEach(x=>$('drop').addEventListener(x,e=>{e.preventDefault();$('drop').classList.remove('drag')}));
$('drop').addEventListener('drop',e=>choose(e.dataTransfer.files[0]));
$('analyze').addEventListener('click',async()=>{if(!selected)return;const b=$('analyze');b.disabled=true;b.textContent='Analyzing…';$('error').textContent='';try{const f=new FormData();f.append('file',selected);const r=await fetch(API+'/api/v1/analyze',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Analysis failed');render(d)}catch(e){$('error').textContent=e.message+' — confirm START_BACKEND.bat is still running.'}finally{b.disabled=false;b.textContent='Analyze program'}});
function render(d){$('program').textContent=d.program_name;$('purpose').textContent=d.purpose;$('summary').textContent=d.business_summary;$('mode').textContent=d.analysis_mode;$('tables').innerHTML=d.tables.length?d.tables.map(x=>`<div class="item"><div class="name">${esc(x.name)}</div><div class="muted">${esc(x.operation)} · ${esc(x.reason)}</div></div>`).join(''):'<span class="muted">None detected</span>';$('deps').innerHTML=d.dependencies.length?d.dependencies.map(x=>`<div class="item"><div class="name">${esc(x.name)}</div><div class="muted">${esc(x.type)}</div></div>`).join(''):'<span class="muted">None detected</span>';$('flow').innerHTML=d.call_flow.map(x=>`<li>${esc(x)}</li>`).join('');$('risks').innerHTML=d.risks.map(x=>`<div class="risk ${esc(x.level)}"><strong>${esc(x.level.toUpperCase())}</strong><div class="muted">${esc(x.description)}</div></div>`).join('');$('results').classList.remove('hidden');$('results').scrollIntoView({behavior:'smooth'})}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}health();
